import UserNavbar from "@/components/dashboard-user/share/UserNavbar"




export const metadata = {
    title: 'User DashBoard',
    description: 'Generated by create next app',
}
export default function UserDashboardLayout({ children }) {
    return (
        <section>
            <UserNavbar />
            {children}
        </section>
    )
}