import UserNavbar from '@/components/userDashboard/share/UserNavbar/UserNavbar'
import { gumelaArabic } from '../../../public/assets/js/fonts'
import { userDashboard } from '@/components/data'
import { Card } from '@/components/ui/card'

export const metadata = {
    title: 'User DashBoard',
    description: 'Generated by create next app',
}
export default function UserDashboardLayout({ children }) {
    return (
        <section>
            <UserNavbar />
            {children}
        </section>
    )
}